// Plain-text report for the solar calculator — same copy/download pattern as
// the tolerance stack-up tool.

import type { SizingResult, SizingSettings } from './engine';
import type { EconomicsResult, EconomicSettings } from './economics';
import { LOAD_CLASS_LABEL } from './catalog';
import { type Currency, fromNgn, formatMoney } from './currency';

function line(label: string, value: string): string {
  return `${label.padEnd(38)}${value}`;
}

/** Never print "NaN" or "Infinity" at a user. */
function num(value: number, digits = 2, suffix = ''): string {
  return Number.isFinite(value) ? `${value.toFixed(digits)}${suffix}` : '—';
}

export function formatSolarReport(
  sizing: SizingResult,
  settings: SizingSettings,
  economics: EconomicsResult | null,
  econSettings: EconomicSettings,
  currency: Currency
): string {
  const out: string[] = [];
  const money = (ngn: number) => formatMoney(fromNgn(ngn, currency), currency);

  out.push('SOLAR SYSTEM SIZING & TECHNO-ECONOMIC ANALYSIS');
  out.push('Generated by creekmechanical.com — browser-only, nothing uploaded.');
  out.push(`Date: ${new Date().toISOString().slice(0, 10)}`);
  out.push('');

  out.push('--- LOAD AUDIT ---');
  for (const l of sizing.audit.lines) {
    out.push(
      `  ${l.name} — ${LOAD_CLASS_LABEL[l.loadClass]}, ${l.qty} x ${l.watts} W x ${l.hours} h = ${l.energyWh.toFixed(0)} Wh/day` +
        (l.loadClass === 'inductive' ? ` (surge x${l.surge} -> ${l.designWatts.toFixed(0)} W design)` : '')
    );
  }
  out.push('');
  for (const c of ['resistive', 'capacitive', 'inductive'] as const) {
    const b = sizing.audit.byClass[c];
    if (b.lineCount === 0) continue;
    out.push(line(`  ${LOAD_CLASS_LABEL[c]}`, `${b.runningWatts.toFixed(0)} W running / ${b.designWatts.toFixed(0)} W design / ${(b.energyWh / 1000).toFixed(2)} kWh`));
  }
  out.push(line('  Total running power', `${(sizing.audit.totalRunningWatts / 1000).toFixed(3)} kW`));
  out.push(line('  Grand total design power', `${(sizing.audit.grandTotalDesignWatts / 1000).toFixed(3)} kW`));
  out.push(line('  Total daily energy', `${(sizing.audit.totalEnergyWh / 1000).toFixed(3)} kWh`));
  out.push('  (R and C count at running power; I counts at running x surge.)');
  out.push('');

  out.push('--- SYSTEM SIZING ---');
  out.push(line('  Inverter', `${(sizing.inverter.ratedWatts / 1000).toFixed(1)} kW @ ${sizing.inverter.systemVolts} V (set by ${sizing.inverter.governedBy})`));
  out.push(line('  Battery bank', `${(sizing.battery.installedWh / 1000).toFixed(1)} kWh — ${sizing.battery.unitCount} x ${settings.batteryUnitVolts} V ${settings.batteryUnitAh} Ah (${sizing.battery.seriesCount}S x ${sizing.battery.parallelStrings}P)`));
  out.push(line('  PV array', `${(sizing.array.arrayWatts / 1000).toFixed(2)} kWp — ${sizing.array.panelCount} x ${settings.panelWatts} W (${sizing.array.seriesPerString}S x ${sizing.array.parallelStrings}P)`));
  out.push(line('  Charge controller', `${sizing.controller.unitCount} x ${sizing.controller.ratedAmps} A ${sizing.controller.type}`));
  out.push(line('  Surge protection', `${sizing.spd.type}, ${sizing.spd.kA} kA — ${sizing.spd.dcVolts} V DC / ${sizing.spd.acVolts} V AC`));
  out.push('');
  out.push('  Cables:');
  for (const c of sizing.cables) {
    out.push(`    ${c.name}: ${c.requiredMm2} mm2 (${c.amps.toFixed(0)} A, governed by ${c.governedBy})`);
  }
  out.push('  Breakers:');
  for (const b of sizing.breakers) {
    out.push(`    ${b.name}: ${b.ratedAmps} A ${b.kind}`);
  }
  if (sizing.warnings.length) {
    out.push('');
    out.push('  WARNINGS:');
    for (const w of sizing.warnings) out.push(`    ! ${w}`);
  }
  out.push('');

  if (economics) {
    out.push(`--- TECHNO-ECONOMIC ANALYSIS (${currency.code}) ---`);
    out.push('  Equations (1)-(13) adapted from Sobamowo & Ojolo (2018); (14) added.');
    out.push('');
    out.push('  (1) Capital cost');
    out.push(line('      Panels', money(economics.capital.panels)));
    out.push(line('      Inverter', money(economics.capital.inverter)));
    out.push(line('      Battery', money(economics.capital.battery)));
    out.push(line('      Charge controller', money(economics.capital.controller)));
    out.push(line('      Balance of system', money(economics.capital.balanceOfSystem)));
    out.push(line('      Mounting', money(economics.capital.mounting)));
    out.push(line('      Installation', money(economics.capital.installation)));
    out.push(line('      Contingency', money(economics.capital.contingency)));
    out.push(line('      TOTAL (C)', money(economics.capital.total)));
    out.push('');
    out.push(line('  (2) Annual energy delivered', num(economics.energy.deliveredKwh, 0, ' kWh/yr')));
    out.push(line('  (3) Annual O&M (M)', money(economics.om.total)));
    out.push(line('      of which battery replacement', money(economics.om.batteryReplacementAnnualised)));
    out.push(line('  (4) Annual revenue (AR)', money(economics.annualRevenue)));
    out.push(line('  (5) Fuel cost (C_F)', money(economics.fuelCost) + (economics.fuelCost === 0 ? '  — zero, solar has no fuel' : '')));
    out.push(line('  (6) Cost per kWh', `${money(economics.costPerKwh)}/kWh`));
    out.push(line('  (7) Annual benefit (B_A)', money(economics.benefit.total)));
    out.push(line('  (8) Payback period', economics.payback.years === null ? `none — ${economics.payback.reason}` : `${economics.payback.years.toFixed(2)} years`));
    out.push(line('  (9) Net present value', money(economics.npv)));
    out.push(line('  (10) Benefit cost ratio', num(economics.bcr, 3)));
    out.push(line('  (11) Internal rate of return', economics.irr === null ? 'no real solution' : `${(economics.irr * 100).toFixed(2)}%`));
    out.push(line('  (12) LCOE', `${money(economics.lcoe.value)}/kWh`));
    out.push(line('  (13) Discount rate (WACC)', num(economics.discountRate * 100, 2, '%')));
    out.push(line('  (14) Simple ROI', num(economics.roi.simple, 1, '%')));
    out.push(line('  (14a) Discounted ROI', num(economics.roi.discounted, 1, '%')));
    out.push(line('  (14b) Annual ROI', num(economics.roi.annual, 1, '%')));
    out.push('');
    out.push('  Notes:');
    for (const n of economics.notes) out.push(`    - ${n}`);
    out.push('');
    out.push(`  System life ${econSettings.lifeYears} yr, battery life ${econSettings.batteryLifeYears} yr,`);
    out.push(`  degradation ${(econSettings.degradationRate * 100).toFixed(2)}%/yr, O&M ${(econSettings.omFraction * 100).toFixed(1)}% of capital.`);
    out.push('');
    out.push('  Component prices and exchange rates are user-editable starting points,');
    out.push('  not quotes. Replace them with real supplier figures before relying on');
    out.push('  any payback or NPV number here.');
  }

  return out.join('\n');
}
